### ISSUE TITLE
Is conditional inclusion of prompts possible? Also embeddings as alternative to hypernetworks?

### ISSUE THREAD

**Issue by hzielke** [mcmonkeyprojects/sd-infinity-grid-generator-script#10]
Can you think of a way to process models which require a specific prompt term that would be prefixed only if the corresponding model is used? (for example voxelArt_v1.ckpt would be triggered with "voxelart")?

Is it also possible to define emmbedded styles instead of hypernetworks?

**Comment by itswhateverman** [comment]
I think for either case you'd need to be able to specify a partial prompt to be prepended or appended to the rest of the prompt passed. neat idea, hope its feasible to implement

**Comment by mcmonkey4eva** [comment]
Yep ^ just do that.

For example, if you use prompt `a picture of a cat (placeholder)`, you can use a field like this:
```yml

model:
    title: Model
    values:
        1:
            title: Base SD
            params:
                model: sd-v1-5-pruned
                PromptReplace: (placeholder)=
        2:
            title: Voxel Art
            params:
                model: voxelart_v1
                PromptReplace: (placeholder)=voxelart
```

Notice how "Base SD" replaces the placeholder with nothing, and "Voxel Art" replaces the placeholder with "voxelart"
