### ISSUE TITLE
Unclear how to specify seed, varseed, varstrength as single value on seed axis

### ISSUE THREAD

**Issue by itswhateverman** [mcmonkeyprojects/sd-infinity-grid-generator-script#11]
I'm trying to understand how to specify variation seeds properly in the yml file.  I thought I could specify as follows similar to a prompt and negative prompt on a prompt axis, but it doesnt seem to use the varseed or varstrength:

```
    seed:
        title: Seed
        values:
            1:
              title: 1
              params: 
                seed: 1
                VarSeed: 2
                VarStrength: 0.01
            2:
              title: 2
              params: 
                seed: 1
                VarSeed: 2
                VarStrength: 0.99
```
I don't necessarily want to put them on separate axes as the seed, the varseed, and the varstrength all in conjunction define a distinct seed value between 2 seeds.

Merry Christmas and thanks again!
