### ISSUE TITLE
Feature suggestion: Per-model parameters

### ISSUE THREAD

**Issue by knoodrake** [mcmonkeyprojects/sd-infinity-grid-generator-script#12]
I use it to generate comprehensive comparison benchmark for the dozens of versions of my self fine tuned models, and it's almost perfect for that. The most important feature I use is the ability to see many prompts (and their searchreplace variants) with all the models in order to check what training parameters allowed better editability of style, subject, or stayed more true to the subject, etc..

One thing that would be perfect for my use case, is the ability to specify parameters on a per-model basis ; just like you specify the model's native resolution right now.

Specifically, dreambooth model A may have been trained on subject prompt SKS with class PERSON, and model B trained with prompt SCROOGEMCDUCK  with class DUCK. 
I would like to be able to write "photo of subject_replaceme class_replaceme on a motorcycle" in my prompts and use `PromptReplace= subject_replaceme = sks` on **model A** and `PromptReplace= subject_replaceme = scroogemcduck` on **model B**.  
Another example would be that a model may have been a bit over trained compared to another and need CFG adjustement, for example, it would be nice to ask to systematically apply a -5 offset to CFG for a given model, or a +5 for another.

Anyway, I'll take this github issue as an opportunity to thank you for that awesome tool. Very nicely done, and very useful.

**Comment by mcmonkey4eva** [comment]
Yep.
What you just described wanting? The whole promptreplace parameter on models thing? Already a thing! You can just already do that. It works!
Same way you put `width: 768` on 2.x or whatever, just do `PromptReplace: replaceme = whatever`

**Comment by valconius** [comment]
I think what he means is, given…
```
axes:
  replace_character:
    title: Replaces default Mary character
    value:
      mary:
        title: Keeps Mary as Mary
        params:
          PromptReplace: mary = mary
      bob:
        title: Mary is now Bob
        params:
          PromptReplace: mary = bob
  models:
    title: Model
    values:
      nai:
        title: NovelAI
        params:
          model: nai
      naiDreamboothWithoutActivation:
        title: NovelAI Dreambooth, no activation string
        params:
          model: nai-db
      naiDreamboothWithActivation:
        title: NovelAI Dreambooth, activation string is Jane
        description: >-
          This is identical to NovelAI unless the word Jane is in the prompt.
        params:
          model: nai-db-activationJane
          PromptReplace: mary = jane
```
… it is ambiguous in which order the PromptReplace operations occur.
