### ISSUE TITLE
Doing multiple simultaneous PromptReplace operations seems impossible

### ISSUE THREAD

**Issue by valconius** [mcmonkeyprojects/sd-infinity-grid-generator-script#15]
Given…
```
axes:
  replaceSomething:
    title: Replaces two somethings at once
    values:
      firstOption:
        title: Makes colors blue and the atmosphere hazy
        params:
        PromptReplace: color = blue atmosphere = hazy
      secondOptions:
        title: Makes animals turtles
        params:
        PromptReplace: animals = turtles
```
…, I find myself lost as to how to proceed; how can I perform multiple PromptReplace operations, and perhaps specify the order in which they occur?
