### ISSUE TITLE
Bug: Metadata parsing fails if filename has multiple period characters

### ISSUE THREAD

**Issue by itswhateverman** [mcmonkeyprojects/sd-infinity-grid-generator-script#21]
Up to this point I've used CFG scale as my final axis in my yml setup, and I've tested with some CFGs including decimal values. This seems to cause the metadata parse to fail:
For example:

```
Image: 114v6b/14/2/none/22/3.8.png, parameters:
metadata parsing failed for part 6: 3
```

**Comment by mcmonkey4eva** [comment]
er... don't have `.` in your keys.

So...
Bad:
`3.8: cfgscale=3.8`
Good:
`3_8: cfgscale=3.8`
Also good:
`literally any text lol it doesn't matter: cfgscale=3.8`
Also fine:
```yml
            38:
                title: 3.8
                description: Three point eight, 3.8
                params:
                    cfg scale: 3.8
```

**Comment by itswhateverman** [comment]
Thanks, now that you point out the issue it makes sense that it would break stuff due to yml 


I had specified it as :
```
axes:
    model: 
    prompt:
    seed:
    hypernetwork:
    steps:
    cfgscale:
        title: CFG Scale
        values:
            3.8: CFG scale=3.8
            4: CFG scale=4            
```

I suppose it got treated as 
```
    cfgscale:
        title: CFG Scale
        values:
            3:
              8: CFG scale=3.8
            4: CFG scale=4
```

Having this present had also broken being able to select between the cfg scale being displayed.
