### ISSUE TITLE
Question: Multiple config per entry

### ISSUE THREAD

**Issue by agilly1989** [mcmonkeyprojects/sd-infinity-grid-generator-script#29]
I was wondering on if (and how) I can set multiple parameters per entry?

Like, I would like to set Height and Width something like the following
```
axes:
  dimensions:
    title: Dimensions
    values:
      landscape: height = 360; width = 640
      portrait: height = 640; width = 360
      square: height = 512; width = 512
```
