### ISSUE TITLE
wrong model loaded with single digit filename

### ISSUE THREAD

**Issue by itswhateverman** [mcmonkeyprojects/sd-infinity-grid-generator-script#3]
I had 2 models, 7.ckpt and 9.ckpt
I specified 9 as below
```
axes:
    model: 
        title: Model
        description: >
                     The model
        values:
            9: model=9
```

(among other values in the yaml)
however when run it loaded 7.ckpt rather than the expected 9.ckpt
