### ISSUE TITLE
Request: export YAML for grid made in the UI

### ISSUE THREAD

**Issue by JS3910** [mcmonkeyprojects/sd-infinity-grid-generator-script#43]
It would be good if we could "get started" with our grid axes and items in the UI and then get a YAML file that we can continue to tweak and add to. The ability to make "quick" grids in the UI is great but this would be very useful.

**Comment by MrSnowman** [comment]
I've done a partial implementation of this here MrSnowman/sd-infinity-grid-generator-script@e3eaf32491c4918028330c6e1d839427317445d6. This branch copies over the yaml file that was used to start generation or it uses the GridFileHelper to extract what's been input in the UI. So it's just what's written in the "Create in UI"-UI at the bottom, no negative prompts, models, prompts, steps or anything else. I'm unsure exactly what to grab. This is effectively a save feature for the UI config and nothing more. That's what I needed when I wrote it. 
It might be helpful for users if they were saved to the assets directory instead so they don't need to copy them over from the output folder.
If the goal is to make the yaml file a perfect reproduction of what's executed when generate is pressed I'm not convinced writing a yaml dumper like I did is the cleanest way.
Example output with two prompt replace axes intended to be used with prompt "tree, nature, season_tag, another_tag":
```yaml
grid:
  title: autonamed_inf_grid_22_03_2023_16_06_05
  author: Unspecified
  description: ''
  format: png
axes:
  prompt_replace:
    title: Prompt Replace
    id: prompt_replace
    description: ''
    values:
      '1':
        title: season_tag=spring
        params:
          promptreplace: season_tag=spring
      '2':
        title: season_tag=winter
        params:
          promptreplace: season_tag=winter
      '3':
        title: season_tag=summer
        params:
          promptreplace: season_tag=summer
  prompt_replace__1:
    title: Prompt Replace
    id: prompt_replace__1
    description: ''
    values:
      '1':
        title: another_tag=happy
        params:
          promptreplace: another_tag=happy
      '2':
        title: another_tag=sad
        params:
          promptreplace: another_tag=sad

```

**Comment by mcmonkey4eva** [comment]
that YAML content is way longer that it needs to be.
The direct transcription from UI to YAML is just:
```yml
axes:
    seed: 1, 2, 3, 4
    steps: 10, 20
```
(and the `grid` block too of course)
