### ISSUE TITLE
Request: configure default axes positions and autoscale

### ISSUE THREAD

**Issue by acorderob** [mcmonkeyprojects/sd-infinity-grid-generator-script#52]
Add settings in the yaml file to set which axes are by default x1, y1, x2 (super), y2 (super), and which value should the auto-scale option be.

**Comment by mcmonkey4eva** [comment]
Added, under `grid`:
```yml
    # Optionally, also specify default choices for the webpage.
    show descriptions: true
    autoscale: false
    sticky: false
    x axis: sampler
    y axis: steps
    x super axis: 'None'
    y super axis: 'None'
```
