### ISSUE TITLE
Add support for including content from other YAML files

### ISSUE THREAD

**Issue by skfoo** [mcmonkeyprojects/sd-infinity-grid-generator-script#87]
When making grids I copy & paste a lot of stuff from an existing grid, like model checkpoint descriptions. Sometimes I'll want to reuse a checkpoint and I'll have to hunt through yamls to find which one had the best parameters for that checkpoint.

If you could specify a YAML file to include in your grid which has data, it would prevent a lot of copy & pasting and make grid definitions a lot smaller.

So I implemented that. I've been using it for a few days and it's been great.

I used [pyyaml-include](https://github.com/tanbro/pyyaml-include) to add support using `!include somefile.yml`. The 'somefile.yml' is a path within the assets directory. 

### Basic Usage

You use it to replace a mapping block with the contents of a yaml file. So if you have a grid file like this,

```
grid:
    params: 
        Sampler: DPM++ 2M Karras
        Steps: 20
        Width: 512
        Height: 768
```

You can extract 'params' into its own file by doing this,

```
grid:
    params: !include usual-parameters.yml
```

Where the contents of 'usual-parameters.yml' is,

```
Sampler: DPM++ 2M Karras
Steps: 20
Width: 512
Height: 768
```

### Includes can Include YAMLs too

A yaml can also include yamls, so you can break out definitions into different files and make yamls that collect stuff for different uses. For example, you can have files like,

```
- checkpoints/
  - everything.yml
  - illustrated.yml
  - checkpoint-anything5.yml
```

The content of 'illustrated.yml' can be

```
anything5: !include checkpoints/checkpoint-anything5.yml
```

And 'checkpoint-anything5.yml' would be:

```
title: Anything5
params:
    model: AnythingV5_v5PrtRE
    vae: orangemix.vae
    clip skip: 2
    cfg: 7
```

In your grid file, you can use either:

```
axes:
    checkpoint:
        values: !include checkpoints/illustrated.yml
```

Or,

```
axes:
    checkpoint:
        values:
            anything5: !include checkpoints/checkpoint-anything5.yml
```

### Limitations

Unfortunately you can't merge mapping values. So you can't do this,

```
axes:
    checkpoint:
        anything5: 
            !include checkpoints/checkpoint-anything5.yml
            skip: true
```

You'll get a syntax error if you try that.
